# -*- coding: utf-8 -*-
import PyQt5
import pygame
# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QVBoxLayout, QLabel, QPushButton, QSlider
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent, QMediaMetaData


class Ui_Form(object):

    def __init__(self):
        self.audio_label = None

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 272)
        Form.setStyleSheet("QWidget {\n"
"                background-color: qlineargradient(spread: pad, x1: 0, y1: 0, x2: 1, y2: 1,stop: 0 rgba(7,0,112,0.916),"
                "stop: 0.27 rgba(11,13,138,0.883), stop: 0.57 rgba(70,32,173,0.916), stop: 0.91 rgba(7,0,112,0.916));}")

        self.setWindowIcon(QtGui.QIcon("musica-romantica.png"))

        self.enviarButton = QtWidgets.QPushButton(Form)
        self.enviarButton.setGeometry(QtCore.QRect(160, 150, 75, 23))
        self.enviarButton.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"MS Shell Dlg 2\",\"Segoe UI\";\n"
"")
        self.enviarButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 30, 221, 41))
        self.label.setStyleSheet("background-color: transparent;\n"
"color: white;\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")

        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(120, 110, 161, 21))
        self.lineEdit.setStyleSheet("background-color: white")
        self.lineEdit.setObjectName("lineEdit")

        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(120, 190, 171, 50))
        self.label_2.setStyleSheet("background-color: transparent;\n"
"color: white;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.label_streak = QtWidgets.QLabel(Form)
        self.label_streak.setGeometry(QtCore.QRect(40, 240, 171, 23))
        self.label_streak.setStyleSheet("background-color: transparent;"
                                      "color: white; font: 75 10pt \"MS Shell Dlg 2\",\"Segoe UI\";\n"
                                      "")
        self.label_streak.setObjectName("label_streak")

        self.pushButton_proximo = QtWidgets.QPushButton(Form)
        self.pushButton_proximo.setGeometry(QtCore.QRect(280, 240, 75, 23))
        self.pushButton_proximo.setStyleSheet("background-color: white;\n"
                                      "font: 75 10pt \"MS Shell Dlg 2\",\"Segoe UI\";\n"
                                      "")
        self.pushButton_proximo.setObjectName("pushButton")


        self.audio_label = QtWidgets.QLabel(Form)
        self.audio_label.setGeometry(QtCore.QRect(15, 186, 171, 23))
        self.audio_label.setStyleSheet("background-color: transparent;"
                                        "color: white; font: 75 10pt \"MS Shell Dlg 2\",\"Segoe UI\";\n"
                                        "")
        self.label_streak.setObjectName("audio_label")

        self.label_nome = QtWidgets.QLabel(Form)
        self.label_nome.setGeometry(QtCore.QRect(135, 250, 175, 25))
        self.label_nome.setStyleSheet("background-color: transparent;"
                                        "color: white; font: 75 6pt \"MS Shell Dlg 2\",\"Segoe UI\";\n"
                                        "")
        self.label_nome.setText("Guilherme de Oliveira Amaral | UDF")
        self.label_nome.setObjectName("label_nome")

        self.slider = QtWidgets.QSlider(Form)
        self.slider.setStyleSheet("background-color: transparent;")
        self.slider.setOrientation(0)  # orientação vertical
        self.slider.move(15, 100)
        self.slider.setMinimum(0)
        self.slider.setMaximum(100)
        self.slider.setValue(50)
        self.slider.setTickInterval(10)
       # self.slider.setTickPosition(QSlider.TicksBelow)
        self.slider.valueChanged.connect(self.onValueChanged)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def onValueChanged(self, value):
        self.audio_label.setText("Volume: {}".format(value))
        volume = value / 100
        pygame.mixer.music.set_volume(volume)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Guess Music"))
        self.enviarButton.setText(_translate("Form", "Enviar"))
        self.pushButton_proximo.setText(_translate("Form", "Próxima"))
        self.label.setText(_translate("Form", "Qual é a música?"))



class CustomDialog(QDialog):
    def __init__(self, title, mensagem, e):
        super().__init__()

        self.setWindowTitle(title)

        layout = QVBoxLayout()

        label_mensagem = QLabel(mensagem)
        layout.addWidget(label_mensagem)

        label_exception = QLabel(str(e))
        layout.addWidget(label_exception)

        ok_button = QPushButton("OK")
        ok_button.clicked.connect(self.accept)
        layout.addWidget(ok_button)

        self.setLayout(layout)
